sources:
  rcsb:
    enabled: true
  bindingdb:
    enabled: false
    extra: {}
  biolip:
    enabled: false
    extra: {}
  chembl:
    enabled: false
  pdbbind:
    enabled: false
    extra: {}
  skempi:
    enabled: false
    extra: {}
